### ISSUE TITLE
Ubuntu 18.04 support for MXNET 

### ISSUE THREAD

**Issue by MuadibTX** [aws/deep-learning-containers#1120]
Hi,

Would it be possible to have the container images for Mxnet be supported on Ubuntu 18.04 (as the other frameworks)?
It seems to be only supporting Ubuntu 16.04

Thanks

**Comment by tejaschumbalkar** [comment]
Hello @MuadibTX 

We currently support MX1.9 with UL20.04. The image URI can be found in [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md)

Can MX1.9 DLC be used in your workflow?

**Comment by tejaschumbalkar** [comment]
Closing the issue. Feel free to re-open if you have additional questions.
