### ISSUE TITLE
Training and inference images have the same tag?

### ISSUE THREAD

**Issue by juliensimon** [aws/deep-learning-containers#1128]
Looking at buildspec files, I see that training are inference images are tagged identically, e.g.:
```
images:
    BuildCPUPTTrainPy3DockerImage:
      ...
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      ...
    BuildCPUPTInferencePy3DockerImage:
      ...
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      ...
```

Is there a good reason for that? Why not add a 'training'/'inference' suffix? This would feel more convenient when building both images. Or are we expected to edit the buildspec files? Am I missing something here? Thanks :)

**Comment by arjkesh** [comment]
Hi @juliensimon - thanks for the question! 

Currently, we expect training and inference images to be held in separate ECR repos - if you look a little higher in the buildspec, you'll see these are referenced under "repository_info"

```
repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
```

If you notice - we have also omitted the ML framework name from the tag - this avoids redundancies in the overall URI.

For an example of what the full ECR uris looks like, check out the example URLs in this markdown file:
https://github.com/aws/deep-learning-containers/blob/master/available_images.md#general-framework-containers

Please let us know if that answers your question, or if you need any further info from us here!

**Comment by arjkesh** [comment]
Hi @juliensimon - closing this ticket out for now. Please let us know if you have any further questions and feel free to reopen if necessary. Thanks for your interest in DLC!
