### ISSUE TITLE
[pending-change] E3/SageMaker container split

### ISSUE THREAD

**Issue by arjkesh** [aws/deep-learning-containers#1291]
## Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the test files this relates to

#### Concise Description:
*Add a concise description of what change needs to be made, why it must be made, and when it must be made*
- In future framework versions, we'll be introducing E3 and SageMaker images, respectively, instead of a single DLC. E3 images will be supported on EC2/ECS/EKS, while SageMaker will include SM packages and be supported on SageMaker.
- We will update this issue with DLCs that will be affected
- Currently, SageMaker containers will be built on top of E3 containers

#### DLC image/dockerfile:
*List of images or dockerfiles that this change applies to*
- PT 1.10 and onwards
- TF 2.7 and onwards
- MXNet 1.9 and onwards 

#### Additional context
*Add any other context about the pending change here.*
- "e3" are for customers running DLCs on ec2/ecs/eks

**Comment by tejaschumbalkar** [comment]
This feature is deployed to production. Closing the issue.
