### ISSUE TITLE
[huggingface_tensorflow, huggingface_pytorch] Release Images

### ISSUE THREAD

**Issue by philschmid** [aws/deep-learning-containers#1326]
# Required Release Image Overview for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 - [ ]  PT 1.8 GPU, transformers==4.10

**inference**:
 - [ ]  PT 1.8 CPU, transformers==4.10
 - [ ]  PT 1.8 GPU, transformers==4.10

## huggingface_tensorflow

**Training**:
 - [x]  TF 2.4 GPU, transformers==4.10

**inference**:
 - [x]  TF 2.4 CPU, transformers==4.10
 - [x]  TF 2.4 GPU, transformers==4.10

---

cc @arjkesh @saimidu

**Comment by philschmid** [comment]
PR is open and ready for review #1286.

**Comment by arjkesh** [comment]
@philschmid can we remove PT1.7 from this ask?

**Comment by arjkesh** [comment]
Requirement - run the dependency check tests manually on release candidates before merge

**Comment by philschmid** [comment]
PR #1286 is merged

**Comment by philschmid** [comment]
Update:
> CVE posted for Pillow in the training containers (both PyTorch training and inference) - this is blocking the mainline pipeline, so we need to add a new PR where we update the Pillow version to 8.3.2 in HF DLCs

**Comment by arjkesh** [comment]
HF TF images have been released

**Comment by arjkesh** [comment]
> Requirement - run the dependency check tests manually on release candidates before merge

Just to document, completed manual run of dependency check tests on both HF TF and PT images.

**Comment by arjkesh** [comment]
HF PT images are released - closing this out

https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.10.2-pt-1.8.1-py36
