### ISSUE TITLE
[huggingface_tensorflow, huggingface_pytorch] Release Images: Framework update

### ISSUE THREAD

**Issue by philschmid** [aws/deep-learning-containers#1355]
# Required Release Image Overview for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 - [x]  PT 1.9 GPU, transformers==4.10

**inference**:
 - [x]  PT 1.9 CPU, transformers==4.10
 - [x]  PT 1.9 GPU, transformers==4.10

## huggingface_tensorflow

**Training**:
 - [x]  TF 2.5 GPU, transformers==4.10

**inference**:
 - [x]  TF 2.5 CPU, transformers==4.10
 - [x]  TF 2.5 GPU, transformers==4.10

**Comment by philschmid** [comment]
PR: #1354

**Comment by arjkesh** [comment]
Dependency check test is re-enabled for HF inference images via https://github.com/aws/deep-learning-containers/pull/1370

**Comment by philschmid** [comment]
PR Merged

**Comment by arjkesh** [comment]
HF TF release is complete https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.10.2-tf-2.5.1-py37

**Comment by arjkesh** [comment]
we have also completed HF PT1.9 release

https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.10.2-pt-1.9.0-py38
