### ISSUE TITLE
[huggingface_tensorflow, huggingface_pytorch] Release Images for Transformers 4.11

### ISSUE THREAD

**Issue by philschmid** [aws/deep-learning-containers#1387]
# Required Release Image Overview for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 - [x]  PT 1.9 GPU, transformers==4.11

**inference**:
 - [x]  PT 1.9 CPU, transformers==4.11
 - [x]  PT 1.9 GPU, transformers==4.11

## huggingface_tensorflow

**Training**:
 - [x]  TF 2.5 GPU, transformers==4.11

**inference**:
 - [x]  TF 2.5 CPU, transformers==4.11
 - [x]  TF 2.5 GPU, transformers==4.11

---

cc @arjkesh @saimidu

**Comment by philschmid** [comment]
PR open #1386

**Comment by arjkesh** [comment]
TF images released https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.11.0-tf-2.5.1-py37

**Comment by arjkesh** [comment]
PT images released - https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.11.0-pt-1.9.0-py38

**Comment by arjkesh** [comment]
@philschmid releases complete
