### ISSUE TITLE
[sanity] fix typing-extensions version for TF2.4 Training DLCs

### ISSUE THREAD

**Issue by junpuf** [aws/deep-learning-containers#1393]
## Checklist
- [ ] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the test files this relates to

#### Concise Description:
TF 2.4.3 sanity check is failing due to `pip check` failing. The failure is related to conflict in dependency package where 

>tensorflow-cpu 2.4.3 has requirement typing-extensions~=3.7.4, but you have typing-extensions 3.10.0.2.

Investigation found that the dependency chain of `typing-extensions` is below:
```
typing-extensions==3.10.0.0
  - importlib-metadata==4.5.0 [requires: typing-extensions>=3.6.4]
    - pluggy==0.13.1 [requires: importlib-metadata>=0.12]
      - pytest==6.2.4 [requires: pluggy>=0.12,<1.0.0a1]
        - dlc-release==0.3.0 [requires: pytest]
    - pytest==6.2.4 [requires: importlib-metadata>=0.12]
      - dlc-release==0.3.0 [requires: pytest]
    - virtualenv==20.4.7 [requires: importlib-metadata>=0.12]
      - pipenv==2020.11.15 [requires: virtualenv]
```
And we can see from above dependency chain, there is no explicit requirement for `typing-extensions~=3.7.4`. Which was why `typing-extensions>=3.6.4` was used by pip and installed version `3.10.0.0`.

We'll need to update the dockerfiles and explicitly install `typing-extensions~=3.7.4`.

#### DLC image/dockerfile:
- [ ] https://github.com/aws/deep-learning-containers/blob/f54ff8ea74f2a6a1d3d63745688fc5c2f60491ed/tensorflow/training/docker/2.4/py3/Dockerfile.cpu#L148
- [ ] https://github.com/aws/deep-learning-containers/blob/f54ff8ea74f2a6a1d3d63745688fc5c2f60491ed/tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu#L230

#### Additional context

Related test: https://github.com/aws/deep-learning-containers/blob/f54ff8ea74f2a6a1d3d63745688fc5c2f60491ed/test/dlc_tests/sanity/test_pre_release.py#L395

**Comment by tejaschumbalkar** [comment]
The dependency for `typing-extensions` on `tensorflow-cpu` package is:
1. `tensorflow-cpu` > `tensorboard` > `markdown` > `importlib-metadata` > `typing-extensions` (required version `>=3.6.4`) 
2. `typing-extensions` (required_version `~=3.7.4`)

The  `typing-extensions` is also a dependent package for `bokeh`, typing-extensions` (required_version `>=3.10.0`). This is where the conflict arises.
