### ISSUE TITLE
Location for the latest Pytorch EI Binaries

### ISSUE THREAD

**Issue by munhouiani** [aws/deep-learning-containers#1428]
Hi,

We would like to build our own deep-learning container and leverage the elastic inference capability. We notice that the official dockerfile install a `pytorch-ei-binaries`, e.g.: `https://pytorch-ei-binaries.s3.us-west-2.amazonaws.com/r1.9.0_inference/20210730-020505/2dc3e2055764606a22a3c59ea955184e85ad6110/cpu/torch-1.9.0-cp38-cp38-manylinux1_x86_64.whl`.

Is there any place we can check for the latest build of that binary?

Thanks

**Comment by pravali96** [comment]
We are going to deprecate Elastic Inference by end of April, 2024. If you are currently using Elastic Inference, you may get better performance at a much better price than Amazon EI with new hardware accelerator options such as AWS Inferentia or the GPU accelerated ml.g4dn.xlarge for your machine learning (ML) inference workloads. Please consider migrating your workloads to options that offer better price and performance. 

Other benefits of using alternatives 
- Amazon Elastic Inference only supports Pytorch 1.5 and Tensorflow 2.3. If you migrate to ml.g4dn instances, you can use the latest versions of Pytorch 1.11 and Tensorflow 2.9 
- ml.g4dn and AWS Inferentia are available in all regions, where as Amazon Elastic Inference is only available in 5 regions. 
- Both AWS Inferentia and ml.g4dn offer better performance at lower price for most ML inference workloads.

See: https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html
