### ISSUE TITLE
[huggingface_tensorflow, huggingface_pytorch] Release Images for Transformers 4.12

### ISSUE THREAD

**Issue by philschmid** [aws/deep-learning-containers#1475]
# Required Release Image Overview for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 - [ ]  PT 1.9.1 GPU, transformers==4.12

**inference**:
 - [ ]  PT 1.9.1 CPU, transformers==4.12
 - [ ]  PT 1.9.1 GPU, transformers==4.12

## huggingface_tensorflow

**Training**:
 - [x]  TF 2.5 GPU, transformers==4.12

**inference**:
 - [x]  TF 2.5 CPU, transformers==4.12
 - [x]  TF 2.5 GPU, transformers==4.12

---

cc @arjkesh @saimidu

**Comment by arjkesh** [comment]
Just want to update here, this is currently blocked on new transformers version

**Comment by arjkesh** [comment]
PR and Issue are ready 11/3

**Comment by arjkesh** [comment]
PR #1474 merged

**Comment by arjkesh** [comment]
release completed https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.12.3-tf-2.5.1-py37

**Comment by philschmid** [comment]
Opened Issue and PR for sdk: 
* https://github.com/aws/sagemaker-python-sdk/pull/2752
* https://github.com/aws/sagemaker-python-sdk/issues/2751

**Comment by arjkesh** [comment]
Release complete for PT: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.12.3-pt-1.9.1-py38
