### ISSUE TITLE
[huggingface_tensorflow, huggingface_pytorch] Release Images: Framework update

### ISSUE THREAD

**Issue by philschmid** [aws/deep-learning-containers#1581]
# Required Release Image Overview for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 - [x]  PT 1.10.2 GPU, transformers==4.17

**inference**:
 - [x]  PT 1.10.2 CPU, transformers==4.17
 - [x]  PT 1.10.2 GPU, transformers==4.17

## huggingface_tensorflow

**Training**:
 - [x]  TF 2.6 GPU, transformers==4.17

**inference**:
 - [x]  TF 2.6 CPU, transformers==4.17
 - [x]  TF 2.6 GPU, transformers==4.17

**Comment by philschmid** [comment]
Split PR into two
* #1630 
* #1629

**Comment by philschmid** [comment]
@saimidu can you post the ETA for the Pytorch release when you know it here?

**Comment by philschmid** [comment]
HF Transformers 4.17.0 PT 1.10 images for training and inference are released — https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.17.0-pt-1.10.2-py38

**Comment by philschmid** [comment]
SageMaker SDK support: 
*  https://github.com/aws/sagemaker-python-sdk/pull/3011

**Comment by bafonso** [comment]
4.20 has some very good benefits such as auto batch size, any idea of when the next update comes for huggingface DL images? :)
