### ISSUE TITLE
[pending-change] Add test to validate DLC major version with production images

### ISSUE THREAD

**Issue by arjkesh** [aws/deep-learning-containers#1623]
## Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the test files this relates to

#### Concise Description:
*Add a concise description of what change needs to be made, why it must be made, and when it must be made*
Pertains to `test_dlc_labels.py`

As we scale out multistage dockerfiles, it will be more robust to check DLC major version against production images, so that we can have multiple major versions defined in the same Dockerfile but still protect against unintentional version mismatches.

**Comment by tejaschumbalkar** [comment]
@arjkesh Is this issue still valid?
