### ISSUE TITLE
Update license of tensorflow 2.7->2.8

### ISSUE THREAD

**Issue by denadai2** [aws/deep-learning-containers#1680]
Hi, I think you need to update the license here

https://github.com/aws/deep-learning-containers/blob/412e3434a14286a98dbe9d68245cd98995de7f2e/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.e3.gpu#L259

**Comment by tejaschumbalkar** [comment]
Thanks for reporting the bug! We will get it fixed in the dockerfile.

**Comment by tejaschumbalkar** [comment]
The [license file](https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu#L264) is updated with the expected version. Closing the issue.
