### ISSUE TITLE
[bug] Torchaudio 0.10.0+cu113 import fails because libtorch_cuda_cpp.so cannot be found

### ISSUE THREAD

**Issue by Quint-e** [aws/deep-learning-containers#1751]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

Importing `torchaudio` version 0.10.0+cu113 fails because `libtorch_cuda_cpp.so` cannot be found. The cause of this issue is unclear to me but I suspect it may be related to the PyTorch build in this AWS DeepLearning Container. 

*DLC image/dockerfile:*
```
763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.10.0-gpu-py38-cu113-ubuntu20.04-sagemaker
```

*Current behavior:*

My Docker file is based on an AWS DeepLearning Container (DLC) in which I add Torchaudio (making sure the version matches PyTorch):
```
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.10.0-gpu-py38-cu113-ubuntu20.04-sagemaker

RUN pip install torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

The container builds with no issue, importing `torch` works but importing `torchaudio` gives an error: 
```
>>> import torch
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_extension.py", line 27, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_extension.py", line 21, in _init_extension
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```

*Expected behavior:*

Torchaudio should import with no issue. 

*Additional context:*

I believe this issue may be related to [https://github.com/aws/deep-learning-containers/issues/1631](https://github.com/aws/deep-learning-containers/issues/1631). 
As proposed by @sitecao in [https://github.com/aws/deep-learning-containers/issues/1631](https://github.com/aws/deep-learning-containers/issues/1631), forcing reinstall of `torch` at the time of installing `torchaudio` resolves the import error:
```
pip install torch==1.10.0+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html --force-reinstall
```
This observation leads me to suspect that the issue may lie with or be related to the `torch` build in this container.

**Comment by krzim-aws** [comment]
I'm betting that building `torchaudio` from sources would resolve the issue as well. I'm not sure what sort of lift that is compared to my solution of installing `torchvision` from sources. 

Unfortunately all of the `torch` binaries in the newest DLCs (`1.9.0` onward) appear to be built without the split CUDA lib files so installing any of the official `torch*` binaries will not work without reinstalling `torch` or without building from source.

**Comment by Quint-e** [comment]
Understood. 
Is there a plan to fix this in future updates of the DLCs, or should we assume it will be the default behaviour from now on?

**Comment by ydaiming** [comment]
@Quint-e
We used to build the aws-pytorch binary in the container. Starting from PT 1.11.0 (pending release) we're building inside CentOS 7, same as the official PyTorch. This `OSError: libtorch_cuda_cpp.so` should go away with new DLCs.
