### ISSUE TITLE
[documentation-request] Suggest to add a note to refer to AWS Doc in the SM Training Compiler containers section

### ISSUE THREAD

**Issue by mchoi8739** [aws/deep-learning-containers#1816]
*Concise Description:*

Each service has different regions that it supports. 
In the [SM Training Compiler containers](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-training-compiler-containers) section, we should document that those containers are available in a subset of AWS Regions.
We have a AWS Doc page to list specific regions that the product is available: https://docs.aws.amazon.com/sagemaker/latest/dg/training-compiler-support.html

Please add the following note in that section:

SageMaker Training Compiler is available in a subset of AWS Regions. For more information, see [Supported Frameworks, AWS Regions, Tested Instances, and Tested Models](https://docs.aws.amazon.com/sagemaker/latest/dg/training-compiler-support.html) in the *SageMaker Training Compiler developer guide*.

**Comment by tejaschumbalkar** [comment]
PR #1826 is merged.
