### ISSUE TITLE
[bug] Missed neuron-start.sh

### ISSUE THREAD

**Issue by maxim-gapchenko** [aws/deep-learning-containers#1818]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
pytorch/inference/docker/build_artifacts/neuron-start.sh is missed, but it is required for neuron containers.

*DLC image/dockerfile:*

*Current behavior:*

*Expected behavior:*

*Additional context:*

**Comment by aws-vrnatham** [comment]
Please use the latest [dockerfile](https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.10/py3/sdk1.19.0/Dockerfile.neuron). neuron_start.sh is replaced with other files.

**Comment by tejaschumbalkar** [comment]
Closing the issue. Feel free to reopen if the above solution does not solve the problem.
