### ISSUE TITLE
[documentation-request] Missing TF 2.8.0 image in the available DLC list

### ISSUE THREAD

**Issue by mchoi8739** [aws/deep-learning-containers#1831]
*Concise Description:*

* While working on updating the SageMaker distributed training documentation, we found that DLC for TF 2.8.0 release is already cut: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-tf-sagemaker-2.8.0-py39
  but this is not listed in [deep-learning-containers/available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md)

**Comment by arjkesh** [comment]
TF sagemaker images are added - https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-framework-containers-sm-support-only
