### ISSUE TITLE
Pytorch elastic inference for pytorch >1.5 

### ISSUE THREAD

**Issue by Shubham-Sharma-09** [aws/deep-learning-containers#2006]
Kindly guide as to how we can deploy Pytorch elastic inference for models utilising Pytorch >1.5. As elastic inference containers which are available support only Pytorch 1.5. I am using Pytorch 1.8 and detectron2 and wish to deploy the same using Pytorch Elastic inference.

**Comment by pravali96** [comment]
We are going to deprecate Elastic Inference by end of April, 2024. If you are currently using Elastic Inference, you may get better performance at a much better price than Amazon EI with new hardware accelerator options such as AWS Inferentia or the GPU accelerated ml.g4dn.xlarge for your machine learning (ML) inference workloads. Please consider migrating your workloads to options that offer better price and performance. 

Other benefits of using alternatives 
- Amazon Elastic Inference only supports Pytorch 1.5 and Tensorflow 2.3. If you migrate to ml.g4dn instances, you can use the latest versions of Pytorch 1.11 and Tensorflow 2.9 
- ml.g4dn and AWS Inferentia are available in all regions, where as Amazon Elastic Inference is only available in 5 regions. 
- Both AWS Inferentia and ml.g4dn offer better performance at lower price for most ML inference workloads.

See: https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html
