### ISSUE TITLE
Why torchvision without cu113?

### ISSUE THREAD

**Issue by elgalu** [aws/deep-learning-containers#2012]
https://github.com/aws/deep-learning-containers/blob/3fd4faef872ad5d76a4a8a36fbfb311874f2acf6/pytorch/training/docker/1.10/py3/cu113/Dockerfile.e3.gpu#L46

If this is for cu113 shouldn't be `0.11.3+cu113` ? 

I would open a PR but `https://framework-binaries.s3.us-west-2.amazonaws.com/pytorch/1.10.2/torchvision-0.11.3+cu113-cp38-cp38-linux_x86_64.whl"` gives 403 Forbidden.

**Comment by josephevans** [comment]
Hi, thanks for reporting this.

For PyTorch [1.11](https://github.com/aws/deep-learning-containers/blob/e554dfbead4d5b0b24613b6b52b07ae5c9a01872/pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu#L9) and [1.12](https://github.com/aws/deep-learning-containers/blob/e554dfbead4d5b0b24613b6b52b07ae5c9a01872/pytorch/training/docker/1.12/py3/cu113/Dockerfile.gpu#L9) DLC releases, we are using the cu113 flavor. Are you able to try these?

**Comment by elgalu** [comment]
Cool! that should do, thanks!
