### ISSUE TITLE
config.properties for hugging face containers 

### ISSUE THREAD

**Issue by aj2622** [aws/deep-learning-containers#2155]
how to I specify my own config.properties to control the serving behavior of in the image `763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04`

**Comment by ShiboXing** [comment]
redirecting to: https://github.com/aws/sagemaker-huggingface-inference-toolkit/issues/65
