### ISSUE TITLE
[feature-request] Support Python 3.9

### ISSUE THREAD

**Issue by CandiedCode** [aws/deep-learning-containers#2156]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Support Python 3.9 

*DLC image/dockerfile:*
https://github.com/aws/deep-learning-containers/tree/master/pytorch/training/docker/1.12/py3
https://github.com/aws/deep-learning-containers/tree/master/pytorch/inference/docker/1.12/py3

*Is your feature request related to a problem? Please describe.*
Pytorch supports python 3.9 and 3.10.  I have some libraries that are dependent on python 3.9 that I can not use.

*Describe the solution you'd like*
Provide published pytorch containers for python 3.9

*Describe alternatives you've considered*
My alternative, is to create my own containers, including some I would like to use for SageMaker.

**Comment by aSabres** [comment]
hey, I have the same problem.
anyone have an update?

We need a pytorch image for training that support python 3.9 and MPI distribution training for a specific job. 
I can just rebuild the image [here](https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.12/py3/Dockerfile.cpu) with python 3.9?

**Comment by tejaschumbalkar** [comment]
Closing the issue. Feel free to re-open if you have additional questions.
