### ISSUE TITLE
[bug] New PyTorch inference image leads to inference job failure

### ISSUE THREAD

**Issue by jpcpereira** [aws/deep-learning-containers#2197]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Following the release [v1.4-pt-1.9.1-inf-py38](https://github.com/aws/deep-learning-containers/releases/tag/v1.4-pt-1.9.1-inf-py38), the inference jobs using this container image started failing.

*DLC image/dockerfile:*
`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:1.9.1-gpu-py38-cu111-ubuntu20.04-v1.4`

*Current behavior:*
When I trigger an inference job that uses the newly released version, it fails with the following message:
```
File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'model'
```

*Expected behavior:*
The inference job is successful.

*Additional context:*
The error does not occur if the previous version of the image is used, _i.e._, [v1.3-pt-1.9.1-inf-py38](https://github.com/aws/deep-learning-containers/releases/tag/v1.3-pt-1.9.1-inf-py38)
`763104351884.dkr.ecr.eu-west-1.amazonaws.com/pytorch-inference:1.9.1-gpu-py38-cu111-ubuntu20.04-v1.3`

**Comment by sirutBuasai** [comment]
Hi, We no longer support PyTorch 1.9 DLCs. We recommend upgrading to later PyTorch DLCs, see [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-framework-containers-sm-support-only) for more information.

Closing this issue for now. Feel free to reopen if you are still observing the issue.
