### ISSUE TITLE
[bug] Inference image definition removed from TF buildspecs with no explanation

### ISSUE THREAD

**Issue by HarryCaveMan** [aws/deep-learning-containers#2459]
*Concise Description:*
BuildSpecs for tf 2.8-2.10 images have had all of the inference image definitions in their specifications commented out with no explanation

*Current behavior:*
Cannot build inference image because all image definitions are commented out in buildspec yaml. Spec still exists but has no images to build.

*Expected behavior:*
Spec both exists and has images defined for inference.

*Additional context:*
Commits:
  - 5b6a03c6d630fcfb9f282f9b53dd48bda9d0ce86
  - ba7d74b444ee95f144ff4a2012608bd9205ebe7d
  - 9da25d820b31919df741fd7bdd9a64246f926670

**Comment by tejaschumbalkar** [comment]
Hello @HarryCaveMan 
We did a split of the training and inference build specifications. The inference buildspecs are hosted in the [deep-learning-containers/tensorflow/inference/](https://github.com/aws/deep-learning-containers/tree/master/tensorflow/inference) folder and it should be uncommented now.

Let me know if you have any other issues.

**Comment by tejaschumbalkar** [comment]
Closing the issue. Feel free to re-open if you have additional questions.
