### ISSUE TITLE
Error in dlopen libtorch_cuda_linalg.so undefined symbol: culibosInit

### ISSUE THREAD

**Issue by elgalu** [aws/deep-learning-containers#2506]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [x] No custom container is required

### Concise Description
Getting Error in dlopen libtorch_cuda_linalg.so undefined symbol: culibosInit when using `kornia.geometry.transform.crop_and_resize()` on the latest `763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2`. Works fine with `763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.12.1-gpu-py38-cu116-ubuntu20.04-ec2`

### DLC image/dockerfile
`763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2`

### Reproduction steps
1. Pull AWS PT 1.13.0 cu117 image

```sh
docker run --rm -ti --gpus=0 "763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2" bash
root@5e2b2957c410:/# pip install kornia==0.6.8
root@5e2b2957c410:/# python
```

2. Reproduce the error

```py
import torch
im_data = torch.ones([120, 3, 367, 254], dtype=torch.int32, device='cuda:0')
bounding_boxes = torch.ones([120, 4, 2], dtype=torch.int32, device='cuda:0')
output_size = (256, 177)

import kornia
kornia.geometry.transform.crop_and_resize(im_data, bounding_boxes, output_size)
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/crop2d.py", line 83, in crop_and_resize
    return crop_by_boxes(tensor, points_src, points_dst, mode, padding_mode, align_corners)
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/crop2d.py", line 226, in crop_by_boxes
    dst_trans_src: torch.Tensor = get_perspective_transform(src_box.to(tensor), dst_box.to(tensor))
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/imgwarp.py", line 361, in get_perspective_transform
    X: Tensor = _torch_solve_cast(A, b)
  File "/opt/conda/lib/python3.9/site-packages/kornia/utils/helpers.py", line 167, in _torch_solve_cast
    out = torch.linalg.solve(A.to(dtype), B.to(dtype))
RuntimeError: Error in dlopen: /opt/conda/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so: undefined symbol: culibosInit
```

### Expected behavior
Not to fail with `undefined symbol: culibosInit` but rather, in this case, throw the proper error `The diagonal element 1 is zero, the solve could not be completed because the input matrix is singular.`

### Additional context
Originally (improperly) reported at https://github.com/kornia/kornia/issues/2080

**Comment by ShiboXing** [comment]
Hi @elgalu, thanks for the issue. It might have something to do with the dynamic cuda linking in our custom made pytorch binary. This symbol should be implemented by the cudatoolkit during cmake. I'll investigate it.

**Comment by ShiboXing** [comment]
@elgalu you can use our newest ec2 image `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2`, in which the pytorch has cuda statically linked. I'll update the available_images list shortly.

**Comment by ShiboXing** [comment]
Hi @elgalu, apologies! I just corrected the above uri. It should be PyTorch 1.13.1.
