### ISSUE TITLE
[feature-request]where to find a page like this deep-learning-containers/available_images.md for cn-north-1, cn-northwest-1 regions? 

### ISSUE THREAD

**Issue by shenshaoyong** [aws/deep-learning-containers#2523]
Checklist
- [ ] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
where to find a page like this deep-learning-containers/available_images.md for cn-north-1, cn-northwest-1 regions? 
*DLC image/dockerfile:*
NA
*Is your feature request related to a problem? Please describe.*
NA
*Describe the solution you'd like*

*Describe alternatives you've considered*
NA
*Additional context*
NA

**Comment by tejaschumbalkar** [comment]
Hello @shenshaoyong 

`cn-north-1` and `cn-northwest-1` regions and respective image uri's are mentioned in the [available-deep-learning-containers-images](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#available-deep-learning-containers-images) section.

Below are the image uri's:

`cn-north-1 `: 727897471807.dkr.ecr.cn-north-1.amazonaws.com.cn/<repository-name>:<image-tag>
`cn-northwest-1`: 727897471807.dkr.ecr.cn-northwest-1.amazonaws.com.cn/<repository-name>:<image-tag>

Let me know if you need any additional information.
