### ISSUE TITLE
[bug] dlc not found when building mxnet image locally

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#263]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
dlc not found
*DLC image/dockerfile:*

*Current behavior:*
```
$ python src/main.py --buildspec mxnet/buildspec.yml \
>                      --framework mxnet \
>                      --image_types training \
>                      --device_types gpu \
>                      --py_versions py3
Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    import utils
  File "/home/ubuntu/deep-learning-containers/src/utils.py", line 22, in <module>
    from dlc.github_handler import GitHubHandler
ModuleNotFoundError: No module named 'dlc'
````

##### Detailed Steps
```
git clone https://github.com/ChaiBapchya/deep-learning-containers.git
cd deep-learning-containers/
pip install -r src/requirements.txt
bash src/setup.sh mxnet
python src/main.py --buildspec mxnet/buildspec.yml --framework mxnet --image_types training --device_types gpu --py_versions py3
```

**Comment by saimidu** [comment]
@ChaiBapchya Thanks for raising this issue. We have an open PR to fix it, which will be merged soon. In the meantime, to unblock your local builds, please make the changes in the same two lines as the PR.

**Comment by saimidu** [comment]
Please find the fix for this bug in the master branch, in the above mentioned PR.

**Comment by ChaiBapchya** [comment]
Thanks!
