### ISSUE TITLE
[bug] codebuild issue

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#265]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

```
python src/main.py --buildspec mxnet/buildspec.yml --framework mxnet --image_types training --device_types gpu --py_versions py3
```

*Additional context:*
```
=================================================================Uploading Metrics================================================================================================================================
[INFO] Found credentials in environment variables.
================================================================================================================================================================================================================================================================================

Traceback (most recent call last):
  File "src/main.py", line 45, in <module>
    image_builder(args.buildspec)
  File "/home/ubuntu/deep-learning-containers/src/image_builder.py", line 202, in image_builder
    test_trigger_job = utils.get_codebuild_project_name()
  File "/home/ubuntu/deep-learning-containers/src/utils.py", line 420, in get_codebuild_project_name
    return os.getenv("CODEBUILD_BUILD_ID").split(":")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by arjkesh** [comment]
Thanks for reporting the issue @ChaiBapchya -- we are working on merging in a fix. In the meantime, you should be able to set CODEBUILD_BUILD_ID to a string value (i.e. "local_test") to unblock local builds.

**Comment by arjkesh** [comment]
Merged in #321 ; tested that this command successfully executes locally `python src/main.py --buildspec mxnet/buildspec.yml --framework mxnet --image_types training --device_types gpu --py_versions py3`

Please reach out again if you are still facing errors, and thank you again for reporting!

**Comment by ChaiBapchya** [comment]
Np. However, to prevent this bug from resurfacing, we should be including a unit-test. What do you think?

**Comment by arjkesh** [comment]
I think it would make more sense to include an integration test to test the local build documentation. I'll follow up with this.
