### ISSUE TITLE
[doc] Documentation on testing for sagemaker tests

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#266]
The readme for the repo: https://github.com/aws/deep-learning-containers/blob/master/README.md

outlines steps for testing locally [for ec2, eks]
Would be great to have documentation for sagemaker tests.

**Comment by Satish615** [comment]
sagemaker Local tests are migrated from their existing github repos. so running the pytest commands will not automatically do the setup. I will send a pr on how to run the do the setup manually.

**Comment by Satish615** [comment]
Sent a pr for the documentation update. https://github.com/aws/deep-learning-containers/pull/300

**Comment by Satish615** [comment]
Pr #300 is Merged.
