### ISSUE TITLE
[huggingface_pytorch, huggingface_tensorflow, huggingface_neuron] Release Training Images for Transformers 4.26

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#2676]
# Overview for *Training* DLCs to update

## huggingface_pytorch

Dependencies versions:
* `transformers: 4.26.0`
* `datasets: 2.9.0`
* `torch: 1.13.1`

- [x] Training - GPU

## huggingface_tensorflow

Dependencies versions:
* `transformers: 4.26.0`
* `datasets: 2.9.0`
* `tensorflow: 2.11.0`

- [x] Training - GPU

## huggingface_pytorch_neuronx

Dependencies versions:
* `transformers: 4.28.1`
* `torch: 1.13.1`
* `torch-neuronx:1.13.0.1.6.1`
* `aws-neuron-sdk 2.9.1`
 
- [x] Training - Neuronx

**Comment by JingyaHuang** [comment]
All PRs for this issue are merged, let's close the issue once all DLCs(only the neuronx one remaining) are released. Thanks @shantanutrip

**Comment by tejaschumbalkar** [comment]
@JingyaHuang Can we close this issue?
