### ISSUE TITLE
[huggingface_pytorch, huggingface_tensorflow, huggingface_neuron] Release Inference Images for Transformers 4.26

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#2677]
# Overview for *Inference* DLCs to update

## huggingface_pytorch

Dependencies versions:
* `transformers: 4.26.0`
* `torch: 1.13.1`

- [x] Inference - CPU
- [x] Inference - GPU

## huggingface_pytorch_neuron

Dependencies versions:
* `transformers: 4.26.0`
* `torch: 1.12.1`
* `torch-neuron >= 1.12.1, < 1.12.2`
* `aws-neuron-sdk` pin to 2.5.0

- [x] Inference - Neuron

## huggingface_tensorflow

Dependencies versions:
* `transformers: 4.26.0`
* `tensorflow: 2.11.0`

- [x] Inference - CPU
- [x] Inference - GPU

**Comment by arjkesh** [comment]
HF PT release complete - https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.26.0-pt-1.13.1-inf-py39

**Comment by arjkesh** [comment]
HF TF release complete - https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.26.0-tf-2.11.0-inf-py39

**Comment by tejaschumbalkar** [comment]
@JingyaHuang Can we close this issue?
