### ISSUE TITLE
[huggingface_pytorch] Release Inference Images for PyTorch 2.0 - Transformers 4.28

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#2837]
# Overview for *Inference* DLCs to update

## huggingface_pytorch

Dependencies versions:
* `transformers: 4.28.1`
* `torch: 2.0.0`
* `diffusers: 0.16.1`

- [x] Inference - CPU
- [x] Inference - GPU

cc. @arjkesh

**Comment by arjkesh** [comment]
Release complete https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-inference-containers
