### ISSUE TITLE
[bug] PyTorch Image incorrectly responds to /ping requests during startup

### ISSUE THREAD

**Issue by public-git-ui** [aws/deep-learning-containers#2917]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Sagemaker Endpoint starts with `InService` status when model loading failed. This might be caused by the /ping from [TorchServe responds with 200 Unhealthy](https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/http/api/rest/InferenceRequestHandler.java#L72), and that the Sagemaker load balancer treats this as healthy, rather than unhealthy. This means the instance is brought in to serve requests before any of its workers are available. When model loading fails randomly, the failed instance/worker does not get replaced.

*DLC image/dockerfile:*

763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.12-cpu-py38

Tested on version 1.9 as well

*Current behavior:*

When model loading failed, container responded with 200 to ping
Endpoint is created with `InService` status when it is non operational

*Expected behavior:*

When model loading failed, container responded with 500 to ping
Deployment should fail if none of the workers can start successfully. Instances with failed workers should be replaced in the load balancer.

*Additional context:*

2 ways to reproduce:

Test case 1:
Deploy an endpoint with an invalid entrypoint. The endpoint will start with IN_SERVICE status

Test case 2:

Use this file `entry_point.py` as entry point:

```
import time

def model_fn(path):
    print("sleeping")
    time.sleep(70)
    print("returning")
    return {}


def predict_fn(request, models):
    return str(request)


def input_fn(request_body, request_content_type):
    return request_body

def output_fn(prediction, content_type):
    return prediction
```
Use this code to deploy:

```
import sagemaker
import boto3
from sagemaker.pytorch.model import PyTorchModel

session = boto3.Session()
sagemaker_session = sagemaker.Session(boto_session=session)
role = sagemaker.get_execution_role(sagemaker_session=sagemaker_session)
bucket = sagemaker_session.default_bucket()
boto_session = boto3.session.Session(region_name='eu-west-1')
artifact_path = f's3://{bucket}/test/dummymodel.tar.gz'
sagemaker_session = sagemaker.Session(boto_session)
sagemaker_model = PyTorchModel(model_data=artifact_path,
                               sagemaker_session=sagemaker_session,
                               role=role,
                               entry_point='entry_point.py',
                               framework_version='1.12',
                               py_version='py38',
                               source_dir='/home/ec2-user/SageMaker/workerfail/code',                             
                               model_server_workers=3,
                               code_location=f's3://{bucket}/code')


endpoint_name = 'example'
sagemaker_model.deploy(initial_instance_count=1,
                               instance_type='ml.m5d.2xlarge',
                               endpoint_name=endpoint_name)

```

Invocation will always failed for Test case 2 as the TorchServe default timeout is less than 70 seconds.

Sample of logs:

```
	2023-04-21T14:48:26.196Z	2023-04-21T14:48:21,637 [INFO ] pool-2-thread-4 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:container-0.local,timestamp:1682088451	AllTraffic/i-0dc3e4662ba8e2d9b
	2023-04-21T14:48:26.836Z	2023-04-21T14:48:26,636 [INFO ] pool-2-thread-4 ACCESS_LOG - /169.254.178.2:36212 "GET /ping HTTP/1.1" 200 0	AllTraffic/i-0dc3e4662ba8e2d9b
	2023-04-21T14:48:30.346Z	2023-04-21T14:48:30,252 [INFO ] W-9001-model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 60001	AllTraffic/i-0dc3e4662ba8e2d9b
i-0dc3e4662ba8e2d9b
	2023-04-21T14:48:30.346Z	2023-04-21T14:48:30,289 [WARN ] W-9000-model_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died.
```

**Comment by public-git-ui** [comment]
This issue would be fixed if the container upgrades to torchserve 0.8 when it's available with this commit: https://github.com/pytorch/serve/pull/2254

**Comment by mohanasudhan** [comment]
Latest PyTorch container is updated with TS 0.8 https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/2.0/py3/Dockerfile.cpu#L12

**Comment by public-git-ui** [comment]
I have tried manually upgrading to torchserve 0.8 and the problem persists. It's possible the `maxRetryTimeoutInSec` setting introduced in this [PR](https://github.com/pytorch/serve/pull/2254) will need to reduce from the default 5 mins.

**Comment by lxning** [comment]
@public-git-ui the default value of "maxRetryTimeoutInSec" is 5min. It can be changed in model-config.yaml per model. Could you please provide the ping endpoint code @14:41:20?

**Comment by public-git-ui** [comment]
The logs have expired now, I think it was 200. I have tried changing model-config.yaml which is a bit tricky because the user does not call TorchArchiver as part of Sagemaker SDK. We ended up implementing a customer Ping plugin which solves the issue during Endpoint updates, i.e. return http 500 until all models are loaded. However, requests are still timing out when the endpoint auto scales up, but it least it would recover after a few minutes or we could over scale.

**Comment by lxning** [comment]
@public-git-ui We do see lots of limitation and error-prone by using [SM PySDK ]([public-git-ui](https://github.com/public-git-ui)). We plan to gradually deprecate it and encourage cx to directly follow [TorchServe instruction](https://docs.aws.amazon.com/sagemaker/latest/dg/deploy-models-frameworks-torchserve.html).

**Comment by public-git-ui** [comment]
Thanks for the instructions, I will close this case now. I have some suggestions for the documentation:
- Add instructions on endpoint update.
- Add instructions for multi container endpoints: https://docs.aws.amazon.com/sagemaker/latest/dg/multi-container-endpoints.html
- Add instruction to control log levels and print logs from worker to stdout so it can be captured by CloudWatch.
