### ISSUE TITLE
[huggingface_pytorch_neuronx] Release Inference Image for PyTorch 1.13.0 - Transformers 4.28

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#2931]
# Overview for *Inference* DLCs to update

## huggingface_pytorch

Dependencies versions:
* `transformers: 4.28.1`
* `torch: 1.13.0`

- [x] Inference - NeuronX

cc. @arjkesh @shantanutrip

**Comment by arjkesh** [comment]
Release complete https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-neuronneuronx-inference-containers
