### ISSUE TITLE
where to specify the model_base_path for TensorFlow Serving

### ISSUE THREAD

**Issue by Ageneinair** [aws/deep-learning-containers#298]
From the [dockerfile](https://github.com/aws/deep-learning-containers/blob/fff4d1edfde40bce298cb2bfe8edd3007cdb604a/tensorflow/inference/docker/2.2.0/py3/Dockerfile.cpu#L115) for creating the TensorFlow Serving, it seems this line just makes a folder, but no model in there. Where do we specify the model path here?

**Comment by nskool** [comment]
Hi, thanks for your interest. Please check the AWS documentation for using the inference container to serve a model: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-ec2-tutorials-inference.html#deep-learning-containers-ec2-tutorials-inference-tf2.

**Comment by Ageneinair** [comment]
From my understanding of this documentation, it downloading the model (from git clone the TensorFlow repo) in the image. But how we update the model after we deploy the whole image on ECS?

**Comment by nskool** [comment]
Hi Ageneinair@, in case of updating running an updated model on ECS, you can check out ECS features such as CRON-based task scheduling: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html, or the update-task api: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/update-task-definition.html. Please checkout ECS documentation for diving deep into your ECS-based use-case: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html
