### ISSUE TITLE
[huggingface_pytorch] Release training Images for PyTorch 2.0 - Transformers 4.28

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#2986]
# Overview for *training* DLCs to update

## huggingface_pytorch

Dependencies versions:
* `transformers: 4.28.1`
* `datasets: 2.12.0`
* `evaluate: 0.4.0`
* `accelerate: 0.19.0`
* `torch: 2.0.0`
* `diffusers: 0.16.1`

- [x] Training - GPU

cc. @saimidu @ShiboXing @arjkesh

**Comment by jld23** [comment]
+1 newer version of DLC are needed.
