### ISSUE TITLE
[bug] Neuronx packages in Neuron Container for Pytorch inf1

### ISSUE THREAD

**Issue by sergioluengo** [aws/deep-learning-containers#3082]
Checklist
- [X] I've prepended issue tag with type of change: [bug]
- [] (If applicable) I've attached the script to reproduce the bug
- [X] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [] (If applicable) I've documented below the tests I've run on the DLC image
- [X] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
The Neuron Container for PyTorch, specifically designed for inf1 instance type, is currently configured with neuronx-cc 2.6.0 instead of neuron-cc[tensorflow].
 
*DLC image/dockerfile:*
763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuron:1.13.1-neuron-py38-sdk2.10.0-ubuntu20.04

*Current behavior:*
Upon executing the pip list command within an interactive terminal in the DLC image the following packages are returned:
 - neuronx-cc                  2.6.0.19+3d819e565
 - neuronx-hwm             2.6.0.0+826e77395

According to the AWS Neuron documentation, the neuronx packages are suitable for trn1 and inf2 instances. However, the inf1 instance type necessitates the installation of neuron-cc[tensorflow], which is currently absent. Consequently, running the command torch.neuron.trace results in the following error:
`ImportError: Dependency "tensorflow" is not installed. Install neuron-cc and its required dependencies using:
pip install --force-reinstall --extra-index-url=https://pip.repos.neuron.amazonaws.com "neuron-cc[tensorflow]"`

Executing the suggested pip install command leads to a new error due to conflicting dependencies as outlined below:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.7.1 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.
neuronx-cc 2.6.0.19+3d819e565 requires numpy<=1.21.6,>=1.20, but you have numpy 1.18.5 which is incompatible.
neuronx-cc 2.6.0.19+3d819e565 requires scipy<=1.7.3, but you have scipy 1.9.3 which is incompatible.
pandas 1.5.3 requires numpy>=1.20.3; python_version < "3.10", but you have numpy 1.18.5 which is incompatible.`

*Expected behavior:*
The expected behavior is that the Neuron Container specifically designed for the inf1 instance type should be configured with the neuron-cc[tensorflow] package, as opposed to the currently utilized neuronx packages.

*Additional context:*
This problem has been observed to occur consistently across multiple regions, including us-west-2, eu-west-1, and eu-west-3.

**Comment by catalin-manciu-aws** [comment]
Thank you for reporting this issue. It's being fixed in https://github.com/aws/deep-learning-containers/pull/3122

**Comment by catalin-manciu-aws** [comment]
https://github.com/aws/deep-learning-containers/pull/3122 was merged and the fixed image has been released
