### ISSUE TITLE
HuggingFace Inference containers are not available in GovCloud (US-East)

### ISSUE THREAD

**Issue by vinayak-shanawad** [aws/deep-learning-containers#3105]
Hi Team,

Greetings!!

We are able to access following HuggingFace inference container in GovCloud (US-West) region.

[442386744353.dkr.ecr.us-gov-west-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04](http://442386744353.dkr.ecr.us-gov-west-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04)

AWS announced the availability of SageMaker in GovCloud (US-East) region early this year ([documentation](https://aws.amazon.com/about-aws/whats-new/2023/01/amazon-sagemaker-aws-govcloud-us-east-region/))

Hence we decided to deploy models on US-East region but we are not able to pull the following inference container in US-East region and getting below error.

[442386744353.dkr.ecr.us-gov-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04](http://442386744353.dkr.ecr.us-gov-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04)

Error: cannot pull [442386744353.dkr.ecr.us-gov-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04](http://442386744353.dkr.ecr.us-gov-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04). Ensure that the role exists and the image was granted pull permission.

Please check if {dlc-aws-account-id} is correct or not, confirm when we can access those images in US-East region.

Thanks & Regards,
Vinayak

**Comment by tejaschumbalkar** [comment]
Hello @vinayak-shanawad 

We host the DLC for `us-gov-east-1` region in a separate AWS account `446045086412`. Can you use this account for the DLC image pull?

**Comment by ohadkatz** [comment]
Hi @vinayak-shanawad, closing this ticket due to inactivity. If you are still facing issues with DLC images in the GovCloud regions, please feel free to reopen this issue.

**Comment by vinayak-shanawad** [comment]
Thanks @tejaschumbalkar 

We are able to pull the docker images.
