### ISSUE TITLE
[bug] Cannot pull images

### ISSUE THREAD

**Issue by adrienthiery** [aws/deep-learning-containers#3115]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html (i.e. here: https://github.com/aws/deep-learning-containers/blob/master/available_images.md)

*Concise Description:*

I'm not able to pull images that should be available

*DLC image/dockerfile:*

`763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-inference:1.13.1-transformers4.26.0-gpu-py39-cu117-ubuntu20.04` and `763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2`

*Current behavior:*

```
$ aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com
Login Succeeded

$ docker pull huggingface-pytorch-inference:1.13.1-transformers4.26.0-gpu-py39-cu117-ubuntu20.04
Error response from daemon: pull access denied for huggingface-pytorch-inference, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

$ docker pull pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2
Error response from daemon: pull access denied for pytorch-inference, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

*Expected behavior:*

Should be able to pull.

*Additional context:*

Originally, I had the error by creating a Sagemaker inference endpoint, and then I tried pulling manually and the images do not seem to be open to be pulled.

Original error on AWS was: 
```
Failure reason
The role 'arn:aws:iam::xxxxx:role/xxxxxxxx' does not have BatchGetImage permission for the image: '763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference@sha256:cd9169563ccd508d6eed9ce526530835b04931e5e298dc97237aa29cc45d030a'.
```

I tried following the proposed solution here: https://github.com/aws/sagemaker-python-sdk/issues/2002#issuecomment-784199284
But it didn't change anything. Which led me to try pulling manually.

**Comment by tejaschumbalkar** [comment]
Hello @adrienthiery 

Thanks for reporting the issue.

The complete ECR image URI is required for the DLC image pull.  

Eg.

```
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com

docker pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.13.1-transformers4.26.0-gpu-py39-cu117-ubuntu20.04

docker pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2
```

Let me know if this solves the issue.

**Comment by adrienthiery** [comment]
Hi @tejaschumbalkar,
Thanks, it seems to work pulling with the full URL from local, but in the meantime, I re-built the docker images and pushed them to my private ECR.
