### ISSUE TITLE
[feature-request] Upgrade MX Horovod version

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#314]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to

*Concise Description:*
Upgrade HVD version from 0.19.0 to v0.19.5

*DLC image/dockerfile:*
https://github.com/aws/deep-learning-containers/blob/master/mxnet/training/docker/1.6.0/py3/example/Dockerfile.gpu#L10

@TusharKanekiDey FYI

**Comment by TusharKanekiDey** [comment]
@ChaiBapchya Thanks. We will create a PR soon for the requested change.

**Comment by TusharKanekiDey** [comment]
The issue has been fixed in #317.
