### ISSUE TITLE
HuggingFace Text Generation Inference Container versions

### ISSUE THREAD

**Issue by mattreyuk** [aws/deep-learning-containers#3213]
The available_images.md file has a section for HuggingFace Text Generation Inference Container, but there doesn't seem to be code in this repo to generate that image. The only version referenced is `0.8.2` which is behind the [latest version](https://github.com/huggingface/text-generation-inference/releases) and missing some big changes. How can I get/build a text generation inference container with the latest version of the HuggingFace library?

**Comment by frankfliu** [comment]
You can find docker file here: https://github.com/awslabs/llm-hosting-container/tree/main/huggingface/pytorch/tgi/docker

**Comment by mattreyuk** [comment]
Thanks @frankfliu I'll try building that. Do you know if AWS plans to push the later versions to ECR?

**Comment by arjkesh** [comment]
Hii @mattreyuk - TGI 0.9.3 is now available - https://github.com/aws/deep-learning-containers/issues/3054

**Comment by mattreyuk** [comment]
Thanks, @arjkesh that covers everything. I'll close the issue.
