### ISSUE TITLE
[question] ARM+GPU support with DLC

### ISSUE THREAD

**Issue by concavegit** [aws/deep-learning-containers#3281]
I was wondering if there are any images that support ARM and GPU support. I see there are graviton images that should support arm, but they are all CPU images. Since there are graviton instances with GPUs, is there a way that I haven't found to use arm with a GPU?

**Comment by tejaschumbalkar** [comment]
Hello @concavegit

Thank you for the interest. We current do not have GPU supported Graviton DLC images. We will discuss and prioritize the the GPU support for Graviton DLC. 

Unfortunately I cannot comment on a timeline for this feature. We will get back to you once we have the Graviton GPU DLC available.
