### ISSUE TITLE
[bug] opencv-python package cannot be updated for PyTorch 2.0.1 SM framework container

### ISSUE THREAD

**Issue by traverso-inspectifai** [aws/deep-learning-containers#3312]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
I wanted to update our workflow from pytorch 1.13.1 to pytorch 2.0.1. I saw, that you included new SM Framework containers on August 30th, so I started testing if my workflow, which is working for pytorch 1.13.1 and python 3.9 was also working with the fresh released pytorch 2.0.1 image.

I am facing a problem when specifying an opencv-python version in my requirements.txt file, which is different to 4.6.0. It seems, that the opencv-python library is installed via conda and pip cannot uninstall nor replace it with a new version.

*DLC image/dockerfile:*
763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0.1-gpu-py310-cu118-ubuntu20.04-sagemaker

*Current behavior:*
When I specify an opencv-python version different to 4.6.0 in my requirements.txt file I get the following message:

`Collecting opencv-python==4.8.0.76 (from -r requirements.txt (line 850))
Downloading opencv_python-4.8.0.76-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 MB 28.7 MB/s eta 0:00:00
Attempting uninstall: opencv-python
Found existing installation: opencv-python 4.6.0
ERROR: Cannot uninstall opencv-python 4.6.0, RECORD file not found. Hint: The package was installed by conda.
2023-09-07 05:09:28,916 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2023-09-07 05:09:28,916 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
2023-09-07 05:09:28,916 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2023-09-07 05:09:28,916 sagemaker-training-toolkit ERROR    InstallRequirementsError:`

*Expected behavior:*
I would expect, I could install any version of opencv-python in the container by specifying this version in the requirements.txt file. With PyTorch 1.13.1 this workflow works.

*Additional context:*

**Comment by usamec** [comment]
"Easy" (I am not saying correct) fix:
At start of your script add:

```
import os                                                                                                          
                                                                                                                   
os.system("conda remove --force opencv")
os.system("pip install ...")
```

**Comment by sirutBuasai** [comment]
PyTorch 2.0.1 is now out of support. We recommend upgrading to later version of PyTorch containers. See [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#ec2-framework-containers-tested-on-ec2-ecs-and-eks-only) for more information.
