### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by celsofranssa** [aws/deep-learning-containers#3394]
Please share the Dockerfile used for building the image [pytorch-training:2.0.1-gpu-py310](https://github.com/aws/deep-learning-containers/blob/master/available_images.md)

**Comment by saimidu** [comment]
Hi @celsofranssa, the dockerfile used to build the PyTorch Training 2.0.1 GPU SageMaker DLC is https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.

Please use docker build target `sagemaker` in the dockerfile.
