### ISSUE TITLE
[feature-request] Sagemaker Triton ARM64 based images

### ISSUE THREAD

**Issue by ngockhanh5110** [aws/deep-learning-containers#3592]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
I am trying to build an arm-based triton server to run on Sagemaker but failed.

*DLC image/dockerfile:*
I attached here my dockerfile for custom image
```yaml
FROM 007439368137.dkr.ecr.us-east-2.amazonaws.com/sagemaker-tritonserver:23.08-py3 as builder

FROM nvcr.io/nvidia/tritonserver:23.08-py3@sha256:46b7f76cfc1fb2dadab11d2e728f8f88626f8448459b689a2c2a2871d044e0f8

COPY --from=builder /opt/nvidia/entrypoint.d/ /opt/nvidia/entrypoint.d/
COPY --from=builder /opt/tritonserver/ /opt/tritonserver/
COPY --from=builder /opt/tritonserver/amazon_cloudwatch_agent/ /opt/tritonserver/amazon_cloudwatch_agent/
COPY --from=builder /etc/cwagentconfig /etc/cwagentconfig
COPY --from=builder /usr/bin/serve /usr/bin/serve
COPY --from=builder /usr/bin/amazon_cloudwatch_agent_setup.sh /usr/bin/amazon_cloudwatch_agent_setup.sh
COPY --from=builder /etc/logrotate.d/amazon_cloudwatch_agent /etc/logrotate.d/amazon_cloudwatch_agent
COPY --from=builder /etc/cron.daily/logrotate /etc/cron.daily/logrotate
COPY --from=builder /opt/aws/amazon-cloudwatch-agent/ /opt/aws/amazon-cloudwatch-agent/
RUN apt-get update && \
    apt-get install -y logrotate && \
    curl -O https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb

RUN echo 'Y' | dpkg -i -E ./amazon-cloudwatch-agent.deb

RUN rm -rf /tmp/* && \
    rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard && \
    rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl && \
    rm -rf /opt/aws/amazon-cloudwatch-agent/bin/config-downloader && \
    rm -rf amazon-cloudwatch-agent.deb
    
RUN mkdir -p /opt/tritonserver/amazon_cloudwatch_agent && \
    pip install --upgrade awscli && \
    echo 'PATH=$PATH:/opt/aws/amazon-cloudwatch-agent/bin' > /root/.bashrc && \
    chmod +x /usr/bin/serve && \
    chmod +x /usr/bin/amazon_cloudwatch_agent_setup.sh && \
    chmod 644 /etc/logrotate.d/amazon_cloudwatch_agent && \
    mkdir -p /etc/cron.hourly && \
    cp /etc/cron.daily/logrotate /etc/cron.hourly/logrotate 

ENV RUN_WITH_IRSA=True
ENV RUN_IN_CONTAINER=True

RUN pip install --upgrade pip
RUN pip install spacy==2.3.9
RUN python3 -m spacy download en_core_web_lg

```

*Describe the solution you'd like*
A build dockerfile of the original sagemaker-triton image
or provide an image with ARM based

*Additional context*
Failed to load on Sagemaker
<img width="1646" alt="image" src="https://github.com/aws/deep-learning-containers/assets/59170495/f6514ba9-c479-4854-b1f3-bc21ca5c1b92">

**Comment by nskool** [comment]
@ngockhanh5110 Did you build the image on an ARM-based instance? The SM Triton container doesn't support ARM yet, but the NGC container does. So as long as you're building the container on ARM it may work since the ARM version of the NGC will be used as Base. The SM Triton container is simply being used for copying some artifacts in your dockerfile. Resolving this, please re-open if necessary.
