### ISSUE TITLE
[feature] Inference Image with PT 2.1 and CUDA 12 support

### ISSUE THREAD

**Issue by Hyprnx** [aws/deep-learning-containers#3775]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

Hi, recently, i built a model on Data Science 3.0 (sagemaker-data-science-310-v1) image on AWS Sagemaker, and i figured that this environment equipped with Pytorch 2.1, as well as CUDA 12.1. And i want to deploy the model that ive built on to SM endpoint.

i have searched for pre-existing container on [Github's site](https://github.com/aws/deep-learning-containers/blob/master/available_images.md), but there are no container contains both Pytorch 2.1 and CUDA 12.1, except for the [DJLServing](763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.25.0-tensorrtllm0.5.0-cu122) one. But unfortunately, i can not make the model run on this container.

I have tried to deploy using the CPU inference container, but since the model is too big, it exceeded the 60 seconds time limit by AWS. Also, i tried to build the model again using CUDA 11.x but the model (WhisperX) refused to run on this CUDA version since it requires libcublas.so.12 to run.

So, as a result, im requesting this container to make things easier for me, i think that many people would need this too 👍 .

I understand that creating a new container would require alot of effort from you guys, so if by any chance you have solutions to use CUDA 11.x with WhisperX, please help.

Thank you in advanced!

**Comment by sallyseok** [comment]
Hello, yes we currently only offer Inference DLCs with CUDA 11, but we are working on adding Inference DLCs with CUDA 12! Although I'm not sure if we will add it for PT 2.1 -- we will be prioritizing the newest PT versions first.
