### ISSUE TITLE
[HuggingFace][Neuronx] DLC for Optimum-neuron 0.0.21 - Neuron SDK 2.18 PyTorch 1.13.1 - Transformers 4.36.2

### ISSUE THREAD

**Issue by JingyaHuang** [aws/deep-learning-containers#3822]
# Overview of  DLCs to update

## *Inference*

- [x] Inference - Neuronx

Dependencies versions:
* `transformers: 4.36.2`
* `torch: 1.13.1`
* `aws-neuron-sdk: 2.18.0`
* `optimum-neuron: 0.0.21`

## *Training*

- [x] Training - Neuronx

Dependencies versions:
* `transformers: 4.36.2`
* `torch: 1.13.1`
* `aws-neuron-sdk: 2.18.0`
* `optimum-neuron: 0.0.21`

cc. @catalin-manciu-aws @arjkesh @philschmid @mmcclean-aws

**Comment by ningziwen** [comment]
@JingyaHuang Neuron 2.18.1 was released last week. Would you like to switch to 2.18.1 instead?
