### ISSUE TITLE
[bug] mpi4py broken in the SageMaker PyTorch 2.3.0 CPU training image 

### ISSUE THREAD

**Issue by shchur** [aws/deep-learning-containers#4090]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:* Importing the `mpi4py` package in Python results in segmentation fault, killing the Python process. 

Command to reproduce:
```bash
docker run -ti 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.3.0-cpu-py311-ubuntu20.04-sagemaker
python -c "from mpi4py import MPI"
```
Output:
```
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........:
MPID_Init(1645)..............:
MPIDI_OFI_mpi_init_hook(1574):
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........:
MPID_Init(1645)..............:
MPIDI_OFI_mpi_init_hook(1574):
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
:
system msg for write_line failure : Bad file descriptor

Segmentation fault (core dumped)
```

*DLC image/dockerfile:* `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.3.0-cpu-py311-ubuntu20.04-sagemaker`

*Current behavior:* Segmentation fault when using the `mpi4py` package. 

*Expected behavior:* The package is imported normally, no segmentation fault occurs.

*Additional context:* The problem with `mpi4py` effectively breaks [PyTorch Lightning](https://lightning.ai/pytorch-lightning) on the SageMaker CPU image. The `from mpi4py import MPI` command [is executed](https://github.com/Lightning-AI/pytorch-lightning/blob/2.3.3/src/lightning/fabric/plugins/environments/mpi.py#L42) at creation of the `ligntining.pytoch.Trainer` object, so the following code also results in a segfault
```bash
pip install lightning
python -c "import lightning.pytorch as pl; pl.Trainer()"
```
Currently, the only way to use PyTorch Lightning on the SageMaker CPU image is to uninstall `mpi4py` package.

**Comment by sallyseok** [comment]
Hi, thank you for pointing out this issue! It's caused by the wrong binary version of mpi4py being installed from conda-forge. The currently installed mpi4py is using impi_rt but we want openmpi. 

Two workarounds:
1. The correct installation command from conda-forge as per the [mpi4py pypi documentation](https://pypi.org/project/mpi4py/#:~:text=%24%20conda%20install%20%2Dc%20conda%2Dforge%20mpi4py%20openmpi)
```
conda uninstall mpi4py
conda install -c conda-forge mpi4py openmpi
python -c "from mpi4py import MPI"    # no issue
```
2. or use pip to install instead
```
conda uninstall mpi4py
pip install mpi4py
python -c "from mpi4py import MPI"    # no issue
```

We are working on fixing this and re-releasing the affected images.

**Comment by arjkesh** [comment]
@shchur thank you again for raising this issue. We've moved the installation from conda to pip and released the following image:

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.3.0-cpu-py311-ubuntu20.04-sagemaker`

https://github.com/aws/deep-learning-containers/releases/tag/v1.8-pt-sagemaker-2.3.0-tr-py311

Please pull the latest image and let us know if there are any further issues from your end!

**Comment by shchur** [comment]
Thank you for the quick fix, @arjkesh @sallyseok! I can confirm that the problem does not appear after pulling the new images, so closing this issue.
