### ISSUE TITLE
[feature-request] Python 3.8 containers

### ISSUE THREAD

**Issue by vgod-dbx** [aws/deep-learning-containers#436]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Hi,

Python 3.8 has been out for 9 months. Is there any plan to support Python 3.8 in the Tensorflow containers? 

*Is your feature request related to a problem? Please describe.*
Our company has upgraded to Python 3.8, so we'd like to have the same Python version in the Sagemaker containers. 

*Describe the solution you'd like*
Have official Tensorflow 2.2.0 + py38 containers for CPU and GPU.

*Describe alternatives you've considered*
We are sending our own Python runtime and libraries into the current py37 containers so we don't run into version mismatch problem. However, as a result, every training job requires a lot more data being uploaded to AWS, which significantly slowed down our development processes.

**Comment by nskool** [comment]
Hi @vgod-dbx. Thanks for your interest. While we'd like to release with an upgraded DLC as early as possible, we typically follow python versions of the upstream framework releases for reliability, compatibility and security reasons. Unfortunately I cannot comment on a timeline for py38 support. We're, however, aware of the increasing need for upgrades and will prioritize accordingly.

**Comment by vgod-dbx** [comment]
Thanks for the reply. FWIW, Python 3.8 is officially supported by Tensorflow since 2.2.

**Comment by tejaschumbalkar** [comment]
Hello
We currently support python3.9 for TF2.11 images. Please checkout [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) for the available image URI's.

Closing the issue, feel free to re-open in case you have any additional questions
