### ISSUE TITLE
[feature-request] Inference image for pytorch 2.5 #4398

### ISSUE THREAD

**Issue by philmod-h** [aws/deep-learning-containers#4404]
The [other issue](https://github.com/aws/deep-learning-containers/issues/4398) was closed without resolution, so I'm reopening one.

*Concise Description:*

We are upgrading our training infra to pytorch 2.5, so we also need the inference image with the same version: 

```
$ docker pull 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.5.0-gpu-py311
Error response from daemon: manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.5.0-gpu-py311 not found: manifest unknown: Requested image not found

$ docker pull 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.5.1-gpu-py311
Error response from daemon: manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.5.1-gpu-py311 not found: manifest unknown: Requested image not found
```

*Describe the solution you'd like*

I tried unsuccessfully to build it myself following the instructions in this repo.

**Comment by Yadan-Wei** [comment]
Please be noted that 
PyTorch 2.5.1 SageMaker and EC2 inference DLCs are released. For the full list of uri please check [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#dlc-available-image-user-guide).
EC2 Inference DLC github release tag: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-ec2-2.5.1-inf-py311
SM Inference DLC github release tag: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-sagemaker-2.5.1-inf-py311
