### ISSUE TITLE
[Documentation] Document Sagemaker Performance tests reproducibility locally

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#447]
1. Make the SM Perf tests reproducible locally
2. Document the steps

@saimidu 

*Concise Description:*

*DLC image/dockerfile:*

*Is your feature request related to a problem? Please describe.*
Tough to reproduce SM Perf tests locally [requires non-trivial hacks] & accesses

*Describe the solution you'd like*
make the code locally reproducible

*Describe alternatives you've considered*
None

*Additional context*
Identified as part of https://github.com/aws/deep-learning-containers/pull/444

**Comment by arjkesh** [comment]
Thanks @ChaiBapchya for reporting the issue -- we will investigate and update this issue when there is a fix available.

**Comment by saimidu** [comment]
Thank you @ChaiBapchya. Closing this issue as the PR to fix this has been merged.
