### ISSUE TITLE
[feature-request] update fastai package to v2

### ISSUE THREAD

**Issue by mattmcclean** [aws/deep-learning-containers#540]
The fastai library has recently had a big overhaul with a major release number v2 (see https://pypi.org/project/fastai/#history & https://www.fast.ai/2020/08/21/fastai2-launch/). Would it be possible to update the PyTorch 1.6 container with the 2.0.x version of fastai ?

Checklist
- [ ] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

*DLC image/dockerfile:*

*Is your feature request related to a problem? Please describe.*

*Describe the solution you'd like*

*Describe alternatives you've considered*

*Additional context*

**Comment by nskool** [comment]
Hi @mattmcclean , thanks for your interest. While I cannot comment on a timeline for releasing an updated DLC with fastai v2, we're tracking this on our end and will update this issue when the release is complete.

**Comment by tejaschumbalkar** [comment]
Hello @mattmcclean 

The latest PyTorch version supported on DLC is `v1.13`. Wanted to check if this request is still valid.

Also, are there any pain points of installing the package on top of DLC in your workflow?

**Comment by tejaschumbalkar** [comment]
Closing the issue. Feel free to reopen the issue.
