### ISSUE TITLE
[bug] tensorflow not detected by pip

### ISSUE THREAD

**Issue by emados** [aws/deep-learning-containers#552]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
@see my initial issue on StackOverflow and my workaround at https://stackoverflow.com/q/63650203/4112200

I'm trying to build my custom DLC image that includes the TF2 Object Detection API using the instructions in https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#install-the-object-detection-api . However, I noticed that running the following part causes the already installed `tensorflow` to be replaced.

```
# From within TensorFlow/models/research/
cp object_detection/packages/tf2/setup.py .
python -m pip install .
```
Even when using `--ignore-installed`. After further investigation, I can see that the package is listed in `/usr/local/lib/python3.7/site-packages/tensorflow/` but isn't detected by `pip` when running `pip list` or `pip freeze` (it only lists the `tensorflow-gpu` module.

Here's my Dockerfile (I tried to remove anything not related to the bug):
```
ARG REPO_LOCATION=763104351884.dkr.ecr.us-east-1.amazonaws.com
FROM ${REPO_LOCATION}/tensorflow-training:2.3.0-gpu-py37-cu102-ubuntu18.04

RUN apt-get update \
  && apt-get install -y \
    unzip

RUN python -m pip install --upgrade pip

RUN mkdir /tensorflow

RUN cd /tensorflow \
  && git clone --progress --verbose https://github.com/tensorflow/models

RUN wget -O /tmp/protoc-3.13.0-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip \
  && echo 'fbebe5e32db9edbb1bf7988af5fed471d22730104bc6ebd5066c5b4646a0949e49139382cae2605c7abc188ea53f73b044f688c264726009fc68cbbab6a98819  /tmp/protoc-3.13.0-linux-x86_64.zip' \
    | sha512sum -c -

RUN mkdir -p /tensorflow/protobuf \
  && unzip /tmp/protoc-3.13.0-linux-x86_64.zip -d /tensorflow/protobuf \
  && rm /tmp/protoc-3.13.0-linux-x86_64.zip

ENV PATH="/tensorflow/protobuf/bin:${PATH}"

RUN cd /tensorflow/models/research/ \
  && protoc object_detection/protos/*.proto --python_out=.

RUN pip install cython \
  && pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

RUN pip install --upgrade protobuf

RUN cd /tensorflow/models/research/ \
  && cp object_detection/packages/tf2/setup.py . \
  && python -m pip install .

ENTRYPOINT ["python", "-c", "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"]
```

Steps to reproduce:
1. Running on p2.xlarge EC2 instance (Deep Learning AMI / Amazon Linux 2)
2. `docker build --tag tmp-img:latest .`
3. `docker run --rm --gpus all -it tmp-img:latest`
4. You'll see warning messages that tensorflow failed to load GPU lib files and "Skipping registering GPU devices"

*DLC image/dockerfile:*
763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.3.0-gpu-py37-cu102-ubuntu18.04

*Current behavior:*
`pip list` and `pip freeze` do not list `tensorflow` as an installed package/module.

*Expected behavior:*
`pip list` and `pip freeze` should list `tensorflow` as an installed package/module.

*Additional context:*

**Comment by sboshin** [comment]
The main issue is the "tensorflow like" install. Tensorflow with GPU support is installed as tensorflow-gpu.
If you need to re-install tensorflow, you can always use the wheel link in the Dockerfile.
https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.3.0/py3/cu102/Dockerfile.gpu#L30

So this behavior is expected because it will list it as tensorflow-gpu instead of tensorflow.
To work around you can re-install the wheel after tensorflow is overwritten.
pip uninstall tensorflow -y && pip install https://aws-tensorflow-binaries.s3-us-west-2.amazonaws.com/tensorflow/r2.3_aws/20200806-080706/gpu/py37/tensorflow_gpu-2.3.0-cp37-cp37m-manylinux2010_x86_64.whl -U

**Comment by arjkesh** [comment]
@emados thanks for raising the issue - does @sboshin's response/workaround resolve this issue for you?

**Comment by emados** [comment]
@sboshin Thank you for the suggested solution.

@arjkesh I can't verify the solution currently, but it seems reasonable and I believe it should work.

You can close the issue now, and I'll try to update it when I'm able to verify the solution, if issue is still writable.

Regards,

**Comment by arjkesh** [comment]
Thanks for the update @emados - closing this issue

**Comment by emados** [comment]
Final update on this, the suggested solution by @sboshin works perfectly for me. Thanks again!
