### ISSUE TITLE
[bug] Sagemaker Remote Test reporting issues

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#589]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
SM Remote Test log doesn't get reported correctly.

Observed in 2 commits of the PR: https://github.com/aws/deep-learning-containers/pull/444

- https://github.com/aws/deep-learning-containers/pull/444/commits/5dd2de96fb6f88707a030fca111ca6585534dbb8
- https://github.com/aws/deep-learning-containers/pull/444/commits/867d3946aabd6e30accde84337e1f76c40211730

*DLC image/dockerfile:*
MX 1.6 DLC

*Current behavior:*
Github shows "pending" status.
CodeBuild logs show "Failed" status.
However, actual codebuild logs doesn't bear Failure log. It terminates abruptly.

```

============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-5.3.5, py-1.9.0, pluggy-0.13.1
rootdir: /codebuild/output/src687836801/src/github.com/aws/deep-learning-containers/test/dlc_tests
plugins: rerunfailures-9.0, forked-1.3.0, xdist-1.31.0, timeout-1.4.2
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I
gw0 [3] / gw1 [3] / gw2 [3] / gw3 [3] / gw4 [3] / gw5 [3] / gw6 [3] / gw7 [3]
```

SM-Cloudwatch log
Navigating to the appropriate SM training log shows that the job ran for 2 hours and ended successfully. It says: 
`mx-tr-bench-gpu-4-node-py3-867d394-2020-09-11-21-28-30/algo-1-1599859900`
```
2020-09-11 23:31:37,755 sagemaker-training-toolkit INFO     Reporting training SUCCESS
```

*Expected behavior:*

1. PR commit status should say Failed if CodeBuild log says Failed
2. CodeBuild log should not abruptly hang. It should print out the error. Currently it just terminates after printing some logs post session start.

*Additional context:*

**Comment by ChaiBapchya** [comment]
@saimidu mentioned that codebuild runs have a timeout of 90min. However, 
- codebuild should have shown status as timed out instead of Failed
- PR commit status should have been failed instead of pending.
So that's still an open issue.

**Comment by tejaschumbalkar** [comment]
Depends on #444

**Comment by arjkesh** [comment]
It appears this issue has been resolved by the PR mentioned above. Closing this ticket out.
