### ISSUE TITLE
[feature-request] add tensorflow-datasets package

### ISSUE THREAD

**Issue by aaronmarkham** [aws/deep-learning-containers#618]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
https://pypi.org/project/tensorflow-datasets/
This datasets package really helpful to have and we'll use it in example notebooks.

*DLC image/dockerfile:*
Any future TF release, and add it to patch releases of existing versions.
https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.3.0/py3/Dockerfile.cpu

**Comment by aaronmarkham** [comment]
Used here: https://github.com/aws/amazon-sagemaker-examples/pull/1605

**Comment by tejaschumbalkar** [comment]
Thank you for the request. We include the `tensorflow-datasets` pacakge in the tensorflow training images.

**Comment by tejaschumbalkar** [comment]
Closing the issue, feel free to re-open in case you have any additional questions.
