### ISSUE TITLE
Pytorch Version Mismatch

### ISSUE THREAD

**Issue by souravagarwal** [aws/deep-learning-containers#625]
Hi, I am using one of the available containers in my docker like this 

`FROM 763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-inference:1.4.0-gpu-py36-cu101-ubuntu16.04`

and running a training job using the sagemaker Estimator.

In my training job, when i `print(torch.__version__)` i am getting 0.4.0

Can someone help me resolve this issue?

Thanks!

**Comment by saimidu** [comment]
Hi @souravagarwal thanks for opening this issue. I have tried to reproduce this problem with the docker image above, by running this command:
```
docker run -it 763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-inference:1.4.0-gpu-py36-cu101-ubuntu16.04 'python -c "import torch; print(torch.__version__)"'
```
but I have gotten `1.4.0` as the response.

Could you provide more information on how you arrived at this issue?

**Comment by souravagarwal** [comment]
HI Aplogies for this. When i use this i also get `1.4.0`. I was earlier trying with this image `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04`, where i was getting 0.4.0. Interestingly `pytorch-training` was giving this issue but `pytorch-inference` works properly, even if i am creating a custom docker to train my model.

**Comment by saimidu** [comment]
Tried the same command on the PyTorch Training 1.6.0 image as well:
```
docker run -it 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04 'python -c "import torch; print(torch.__version__)"'
```
and got `1.6.0` as the response.

It is possible that I am not following the exact sequence of steps which produced `0.4.0` on your end. Could you give me a series of steps to follow so that I can try to reproduce the issue?

**Comment by arjkesh** [comment]
Hi @souravagarwal - we are closing this issue out since we haven't heard a response in awhile. Please feel free to reopen if you have any further questions or concerns. Thanks for using DLC!
