### ISSUE TITLE
[feature] Mechanism for skipping tests for specific versions of a framework

### ISSUE THREAD

**Issue by choidongyeon** [aws/deep-learning-containers#652]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*  Please introduce something like a helper function to skip certain tests for framework versions where the functionality being tested does not exist.

*DLC image/dockerfile:* I am using the PyTorch 1.5.1 DLCs provided in the link above.

*Is your feature request related to a problem? Please describe.*
Certain tests will always lead to failures in the PR. For example, [native AMP was introduced by PyTorch in the framework version 1.6](https://pytorch.org/blog/pytorch-1.6-released/). Because of this, a PR introducing changes to the PyTorch 1.5.1, the EC2 test results do not provide an accurate results, as can be seen in this PR https://github.com/aws/deep-learning-containers/pull/650.

*Describe the solution you'd like*
There seems to be no intuitive way to skip tests for specific version numbers of a framework. A helper function or flag that disables tests depending on the framework version (i.e. lower/higher than 1.6) will be helpful.

*Describe alternatives you've considered*

*Additional context*

**Comment by SergTogul** [comment]
Hi Donna, 

Although it's not a one-liner, we have a useful workaround:

1. You can extract a framework version from image tag using `get_framework_and_version_from_tag() `
2. Then comparing current image version with a threshold you can skip a test conditionally. 

I hope this helps.
