### ISSUE TITLE
[feature-request] Include AWS ml-io in training containers

### ISSUE THREAD

**Issue by athewsey** [aws/deep-learning-containers#674]
Checklist
- [X] I've prepended issue tag with type of change: [feature]
- [ ] ~(If applicable) I've documented below the DLC image/dockerfile this relates to~
- [ ] ~(If applicable) I've documented the tests I've run on the DLC image~
- [X] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

AWS Labs' [ml-io library](https://github.com/awslabs/ml-io) is a useful tool for model training but cannot be pip installed via requirements.txt, so would be beneficial to include in base DLC training images and in particular those for PyTorch.

*DLC image/dockerfile:*

Particularly relevant to all **PyTorch training containers**, because:

- MXNet has native RecordIO support, which helps with loading some of the standard SageMaker data formats
- TensorFlow has `PipeModeDataset` through the pip-installable [sagemaker tensorflow extensions](https://github.com/aws/sagemaker-tensorflow-extensions), which also helps tackle some of these use cases

...but may be useful for edge cases across all training containers.

*Is your feature request related to a problem? Please describe.*

ml-io provides a high-performance, low-code-complexity option to *performantly* read a range of data types into training jobs... that might be non-trivial to load via other tools.

For e.g:
- Ouickly iterating through a CSV in numpy mini-batches, or images as numpy arrays
- Reading **RecordIO files** such as SageMaker Augmented Manifests into numpy arrays, or with zero-copy conversion to PyTorch tensors

...But as noted on the project's GitHub README - ml-io can't be installed via pip because of the non-Python dependencies.

It's frustrating to have difficulties loading data from SageMaker-specific formats, and a library tool also authored by AWS that could solve the prooblem - but to have to go through additional non-trivial steps derive a custom container from the provided DLCs and use that custom container with the SageMaker SDK. 

*Describe the solution you'd like*

ml-io core library and Python binding to be pre-installed on DLC training container images, particularly the PyTorch images, to provide an easier route to loading complex/non-PyTorch-native dataset formats without resorting to inefficient Python-based solutions that will likely bottleneck training.

*Describe alternatives you've considered*

- Maybe framework containers could provide some user-friendly way to install conda packages as well as pip?
- Perhaps ml-io is not the best tool for this, but there exists something else that we'd recommend for these kinds of tasks?

*Additional context*

I have a couple of PyTorch scenarios in SageMaker where I'm considering ml-io based solutions: One using AugmentedManifests for bounding box detection in images (SM Ground Truth format), and one just investigating how to efficiently train on larger-than-memory CSV files maybe with some vectorized transformations on batches as they load.

**Comment by SergTogul** [comment]
Hi Alex,

I'm sorry, it's not really clear from the question - since there is an option to install package using conda, have you tried to customize a container? We have instructions [here](https://github.com/aws/deep-learning-containers/blob/master/custom_images.md) and [here](https://github.com/aws/deep-learning-containers/blob/master/custom_images.md). 
Please confirm if that helps.

**Comment by arjkesh** [comment]
Hi @athewsey - please let us know if you need any further help here by reopening this ticket. Since it's been inactive for awhile, we will close it out. Thanks for your interest in DLC!
