### ISSUE TITLE
[feature-request] Support for multiple CUDA versions in buildspec.yml file

### ISSUE THREAD

**Issue by satishpasumarthi** [aws/deep-learning-containers#687]
Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
The current design of buildspec supports only one version of CUDA. Can we get a provision of handling multiple CUDA versions so that framework teams have the option of creating 1 PR and releasing everything in it?
Now that TF2.4 is coming up, it would be good to have this feature.
Tagging @saimidu as he knows some context here. 

*DLC image/dockerfile:*

*Is your feature request related to a problem? Please describe.*

*Describe the solution you'd like*

*Describe alternatives you've considered*

*Additional context*

**Comment by saimidu** [comment]
@satishpasumarthi Thank you for creating this feature-request. We plan to implement support for multiple CUDA versions on the same buildspec in the future, but we are currently prioritizing other improvements to the build process.

I will keep this Issue open, and will keep it updated with more information once we begin work on this improvement.

**Comment by saimidu** [comment]
Addressed by https://github.com/aws/deep-learning-containers/pull/798
