### ISSUE TITLE
[bug]'BatchGetImage permission' error when deploying SageMaker endpoint by using Tensorflow base image

### ISSUE THREAD

**Issue by lu-liu-rft** [aws/deep-learning-containers#759]
I have a pre-trained Tensorflow model, I'm trying to using SagaMaker `client.create_endpoint()` to create an endpoint so that I can call the API to get predictions, the doc is [here][1]

After creating the model by using `client.create_model()` I have a model stored on SageMaker, and the base image I'm using is `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:1.15.2-gpu`

  [1]: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_endpoint

After running this, I'm able to create the endpoint configuration, but it failed to create the endpoint, reason:
```
Failure reason
The role 'arn:aws:iam::9111xxxxxxxx:role/test-role' does not have BatchGetImage permission for the image: '763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:1.15.2-gpu'.
```

In the policy of this role, I have:
```
{
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchGetImage"
            ],
            "Resource": [
                "arn:aws:ecr:us-east-1:763104351884:repository/*sagemaker*"
            ]
        },

        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchDeleteImage",
                "ecr:UploadLayerPart",
                "ecr:DeleteRepository",
                "ecr:PutImage",
                "ecr:SetRepositoryPolicy",
                "ecr:BatchGetImage",
                "ecr:CompleteLayerUpload",
                "ecr:DeleteRepositoryPolicy",
                "ecr:InitiateLayerUpload"
            ],
            "Resource": [
                "arn:aws:ecr:*:*:repository/*sagemaker*"
 ]
        }
....
```
Am I missing anything in the policy? Might someone be able to help please? Many thanks.

**Comment by adrienthiery** [comment]
Related to https://github.com/aws/sagemaker-python-sdk/issues/2002 

I seem to have a similar issue, and tried the fix mentioned on above-mentioned issue, to no avail.

Will continue my search before opening a new issue.

**Comment by MundNic** [comment]
Have you found a solution?

**Comment by MundNic** [comment]
Thanks for your help, I'll try that!
