### ISSUE TITLE
[bug] Only 1 CPU is available in pytorch containers after deploy

### ISSUE THREAD

**Issue by romavlasov** [aws/deep-learning-containers#791]
*Concise Description:*
In the pytorch containers after deploying on SageMaker only 1 CPU is available.

*DLC image/dockerfile:*
Image: "763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:1.6.0-gpu-py3"
Instance: "ml.g4dn.xlarge" (number of vCPU: 4)

*Current behavior:*
In cloudwatch logs only 1 cpu is avaliable:
```
main org.pytorch.serve.ModelServer
Torchserve version: 0.2.1
TS Home: /opt/conda/lib/python3.6/site-packages
Current directory: /
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 1
Max heap size: 3806 M
Python executable: /opt/conda/bin/python
Config file: /etc/sagemaker-ts.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8080
Metrics address: http://127.0.0.1:8082
Model Store: /.sagemaker/ts/models
```

*Expected behavior:*
All 4 CPUs should be available
```
Number of CPUs: 4
```

*Additional context:*
The issue is reproducible with other instance types.

**Comment by ashrielbrian** [comment]
I'm getting this same issue when deployed directly on AWS Fargate containers (without SageMaker). The Fargate container has 2 vCPUs but the logs only show one CPU.

```
main org.pytorch.serve.ModelServer -
Torchserve version: 0.3.0
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /usr/src/app
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 1
Max heap size: 989 M```

**Comment by taepd** [comment]
Is it still not resolved?

**Comment by robertsatya** [comment]
This is still an issue in Torchserve 0.6.0. This is being deployed on g4dn.2xlarge with 8 vCPUs. 

```
2022-12-22T17:12:10,384 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
--
2022-12-22T17:12:10,445 [INFO ] main org.pytorch.serve.ModelServer -
Torchserve version: 0.6.0
TS Home: /opt/conda/lib/python3.8/site-packages
Current directory: /opt/ml/code
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 1
Max heap size: 6919 M
Python executable: /opt/conda/bin/python3.8
```


Is there a fix or workaround to force it to recognize the right number of CPUs available?

**Comment by sirutBuasai** [comment]
We no longer support PyTorch 1.6 containers. We recommend upgrading your containers to later version, see [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-framework-containers-sm-support-only) for more information.

Closing issue. Feel free to reopen if issue is still observed in newer images.
