### ISSUE TITLE
[bug] Torch doesn't see CUDA in latest Pytorch1.6-CUDA101 container

### ISSUE THREAD

**Issue by vdabravolski** [aws/deep-learning-containers#794]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [x] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04 seems to have CUDA drivers misconfigured. I'm getting `False` when i'm running `python -c "import torch; print(torch.cuda.is_available())"` inside container.

*DLC image/dockerfile:*
At least pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04, but can be other containers too.

*Current behavior:*
Torch doesn't see CUDA installed/configured. `python -c "import torch; print(torch.cuda.is_available())"` returns `False`

*Expected behavior:*
`python -c "import torch; print(torch.cuda.is_available())"` returns `True`

*Additional context:*

Sample dockerfile:
```
FROM 763104351884.dkr.ecr.$REGION.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04
RUN python -c "import torch; print(torch.cuda.is_available())"
```

**Comment by ChaiBapchya** [comment]
Unable to reproduce on my end for us-west-2
```
$ docker run -it 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04 bash
$ python -c "import torch; print(torch.cuda.is_available())"
True
```
