### ISSUE TITLE
[bug] ECR Get Login logs into the wrong account when run locally

### ISSUE THREAD

**Issue by saimidu** [aws/deep-learning-containers#899]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
In https://github.com/aws/deep-learning-containers/blob/eae9404b68608b5fc9a54584cb43e0d1ab8236be/test/test_utils/ec2.py#L445, the `aws ecr get-login` command logs into the ECR Registry owned by the AWS Account ID running the test script, and not the ECR Registry that contains the docker image being tested.

This works in automated PRs on CI and CD, but local test attempts to run tests on images held in other accounts/regions will cause the test to fail with `no basic auth credentials`.

*DLC image/dockerfile:*
N/A

*Current behavior:*
Docker Login credentials created are for registry owned by EC2 instance owner

*Expected behavior:*
Docker Login credentials created should be for registry owned by ECR docker image owner

*Additional context:*

**Comment by tejaschumbalkar** [comment]
@saimidu does this issue still exist?

**Comment by sirutBuasai** [comment]
This should be fixed from this [PR](https://github.com/aws/deep-learning-containers/pull/3760)
