### ISSUE TITLE
Sagemaker - training failure for deeplab and psp, but works for fcn

### ISSUE THREAD

**Issue by ssnirgudkar** [aws/deep-learning-containers#902]
Hello, 

I am trying to run semantic segmentation on a bunch of images using amazon inbuilt algorithm. I am getting failures for deeplab and psp. There's no additional information in the cloudwatch logs. Can you help in why I am getting these errors? 
Details - 
Input Image size - height:512, width:640 
Image format - grayscale png 
I am keeping the default crop size - 240 

Configuration 1 -  This works 
backbone - resnet50 
algorithm - fcn 

*Configuration 2 - This fails 
backbone - resnet50 
algorithm - deeplab
Failure - 
ERROR 140452895745216] [14:07:22] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x.2825.0/AL2_x86_64/generic-flavor/src/src/operator/nn/concat.cc:66: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [1,0,64,80], got [1,256,30,30]

*Configuration 3 - Fails - 
backbone - resnet50 
algorithm - psp 
ERROR 140536468395200] [15:05:34] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x.2825.0/AL2_x86_64/generic-flavor/src/src/operator/nn/concat.cc:66: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [1,0,64,80], got [1,512,30,30]

**Comment by zhimin-z** [comment]
what are the configs after all?

**Comment by tejaschumbalkar** [comment]
Closing the issue given it was reported 3 years ago. Feel free to reopen if the issue still exist.
