### ISSUE TITLE
[pending-change] Re-enable TF 2.4.1 CPU Inference EC2 Benchmark test

### ISSUE THREAD

**Issue by saimidu** [aws/deep-learning-containers#918]
## Checklist
- [x] I've prepended issue tag with type of change: [feature]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the test files this relates to

#### Concise Description:
We skipped the TF 2.4.1 CPU Inference EC2 Benchmark test until it can be fixed when run on CI/CD. It completes correctly outside the CI/CD context when run locally. Therefore, we need a fix in the test orchestration step, followed by re-enabling this benchmark test.

#### DLC image/dockerfile:
N/A

#### Additional context
https://github.com/aws/deep-learning-containers/pull/893/files#diff-8d8a9a41a0b7bf5356dba4c821150ad6c7d7c045499442eb9d10d56da730e403R31-R33

**Comment by tejaschumbalkar** [comment]
TF 2.4 is out of support. Closing the issue.
