### ISSUE TITLE
[Question] EIA + MXnet use to deploy model on Sagemaker

### ISSUE THREAD

**Issue by monitarb** [aws/deep-learning-containers#974]
Hi,
I have a model already trained in MXNet using Gluon.  I've deployed it and used it as a Sagemaker endpoint using a p3.2xlarge instance which was toooooo expensive.  Now I'm trying to deploy an endpoint using Elastic Inference and I'm struggling a bit with this.

This is my create/deploy sentence:
```
print('Creating Endpoint: ', endpoint_name)
model = MXNetModel(
    entry_point='entrypoint.py',
    model_data=model_data_s3_uri,
    framework_version='1.4.1', 
    py_version='py3',
    role=sagemaker.get_execution_role()
)

print('Deploy Endpoint: ', endpoint_name)
predictor = model.deploy(endpoint_name=endpoint_name, 
                         initial_instance_count=1, 
                         instance_type='ml.m4.2xlarge',
                         accelerator_type='ml.eia2.medium')
```
Where model_data_s3_uri is the S3 location of the tar.gz containing my params file..  Also this is the loading function inside my entrypoint.py file:
```
def model_fn(model_dir):
    ctx = mx.eia()
    model = gcv.model_zoo.get_model('ssd_300_vgg16_atrous_custom', classes=CLASSES, ctx=ctx
                              pretrained=False, pretrained_base=False)
    model.load_parameters('ssd_512_vgg16_atrous_voc_best.params', ctx, ignore_extra=True)
    return model, ctx
```
I understand that, just by adding the **accelerator_type** parameter, Sagemaker will use the correct MXNet+EIA instance from this repo? And I checked the Docker file and it includes GluonCV.  But it's not working!  The endpoint seems to be deployed succesfully after 8min, but whenever I try to use it (Like I've used it before) I'm getting the error:
**"Error hosting endpoint receti-model-20210304-030842: Failed. Reason:  The primary container,accelerator for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint..."**

And if I check my CloudWatch logs it seems the problem is:
**[INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - AttributeError: 'NoneType' object has no attribute 'transform'**
It seems the model couldn't be loaded (NoneType), so it obviously can't transform the input.

I don't know if I'm understanding correctly, or if I'm doing something wrong. What would be the correct use to deploy an MXNet + GluonCV + AEI model using any of the images of this repo (in case it doesn't get used by default)?

**Comment by pravali96** [comment]
We are going to deprecate Elastic Inference by end of April, 2024. If you are currently using Elastic Inference, you may get better performance at a much better price than Amazon EI with new hardware accelerator options such as AWS Inferentia or the GPU accelerated ml.g4dn.xlarge for your machine learning (ML) inference workloads. Please consider migrating your workloads to options that offer better price and performance. 

Other benefits of using alternatives 
- Amazon Elastic Inference only supports Pytorch 1.5 and Tensorflow 2.3. If you migrate to ml.g4dn instances, you can use the latest versions of Pytorch 1.11 and Tensorflow 2.9 
- ml.g4dn and AWS Inferentia are available in all regions, where as Amazon Elastic Inference is only available in 5 regions. 
- Both AWS Inferentia and ml.g4dn offer better performance at lower price for most ML inference workloads.

See: https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html
