### ISSUE TITLE
[test] Add more tests for non SAGE_PORT ENV var scenario

### ISSUE THREAD

**Issue by schenqian** [aws/deep-learning-containers#985]
#### Concise Description:
*Currently we do not cover the test for not setting up SAGE_PORT ENV var scenario, which would lead to AttributeError: 'ServiceManager' object has no attribute '_tfs_grpc_port_range' issue*
*Related fix: https://github.com/aws/deep-learning-containers/pull/980 and aws/sagemaker-tensorflow-serving-container#194*

**Comment by saimidu** [comment]
After having added tests, we can now resolve this GitHub Issue.
